version: '3'
services:
  jupyter:
    build: .
    ports: 
      - '8888:8888'
    volumes:
      - './:/home/jovyan'
    environment:
      - SLACK_INCOMING_WEBHOOK_URL=$SLACK_INCOMING_WEBHOOK_URL
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - JUPYTER_PASSWORD_HASH=$JUPYTER_PASSWORD_HASH
      - GOOGLE_SERVICE_ACCOUNT_JSON_PATH=$GOOGLE_SERVICE_ACCOUNT_JSON_PATH
      - GOOGLE_CLOUD_STORAGE_BUCKET=$GOOGLE_CLOUD_STORAGE_BUCKET
      - SLACK_WEBHOOK_URL=$SLACK_WEBHOOK_URL
      - GOOGLE_STACKDRIVER_URL=$GOOGLE_STACKDRIVER_URL
      - SLACK_NOTIFY_RECIEVE_USER=$SLACK_NOTIFY_RECIEVE_USER
  tensorboard:
    build: .
    ports:
      - '3000:3000'
    command: tensorboard --host=0.0.0.0 --port=6006 --logdir==logs
